telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:8881781889:AAFDnJSfwQDCYRurwcUDXQ7b-IaHdfL4y-U}
    username: ${TELEGRAM_BOT_USERNAME:vibe_matcher_official_bot}

user-service:
  base-url: ${USER_SERVICE_BASE_URL:http://localhost:8081}

activity-service:
  base-url: ${ACTIVITY_SERVICE_BASE_URL:http://localhost:8082}