spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/interest_founder_sessions
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: ${SERVER_PORT:8081}